---
- name: 'Create .vim directory'
  file:
    path: "{{ home_directory }}/.vim"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
    state: directory

- name: 'Create .vim subdirectory'
  file:
    path: "{{ home_directory }}/.vim/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
    state: directory
  loop:
    - autoload
    - bundle

- name: 'Download and install pathogen'
  get_url:
    url: 'https://tpo.pe/pathogen.vim'
    dest: "{{ home_directory }}/.vim/autoload/pathogen.vim"
    mode: '0644'

- name: 'Copy vimrc'
  copy:
    src: 'vimrc'
    dest: "{{ home_directory }}/.vimrc"
    owner: "{{ username }}"
    mode: '0644'

- name: 'Install vim-better-whitespace'
  git:
    repo: "https://github.com/ntpeters/vim-better-whitespace.git"
    dest: "{{ home_directory }}/.vim/bundle/vim-better-whitespace"

- name: 'Install vim-ansible-yaml'
  git:
    repo: 'https://github.com/pearofducks/ansible-vim.git'
    dest: "{{ home_directory }}/.vim/bundle/ansible-vim"

- name: 'Install vim-json'
  git:
    repo: 'https://github.com/elzr/vim-json.git'
    dest: "{{ home_directory }}/.vim/bundle/vim-json"

- name: 'Install vim-terraform'
  git:
    repo: 'https://github.com/hashivim/vim-terraform.git'
    dest: "{{ home_directory }}/.vim/bundle/vim-terraform"

- name: 'Install vim-dockerfile'
  git:
    repo: 'https://github.com/ekalinin/Dockerfile.vim.git'
    dest: "{{ home_directory }}/.vim/bundle/Dockerfile"

- name: 'Install tabular'
  git:
    repo: "https://github.com/godlygeek/tabular"
    dest: "{{ home_directory }}/.vim/bundle/tabular"
