"-------------------------------------------------
"  vimrc file for ed lim
"  @author - Ed Lim <limed@sudoers.org>
"-------------------------------------------------
call pathogen#infect()

"------------ editor behaviour block ------------------
set shiftwidth=4                " Use 4 spaces when text is indented
set softtabstop=4
set tabstop=4                   " sets how many spaces a tab is
set smarttab
set expandtab
set autoindent                  " auto indent
set smartindent                 " smart indent
set ruler                       " show curser position at all times
set incsearch                   " incremental search
set nohlsearch                  " no highlight on searching
set nowrap                      " no text wraps
set backspace=indent,eol,start  " allow backspacing over everything in insert mode
set term=ansi                   " set term to ansi
set noerrorbells                " do not beep on errors
set ttyfast                     " Smoother scrolling
set virtualedit=all             " allows curser to roam freely
set backspace=2                 " allows backspacing over everything
set showmode                    " show current mode you are in
set showcmd                     " display incomplete commands
set showmatch                   " show matching braces
set undolevels=500              " set the number of undo's
set novisualbell                " no sound on error
set title                       " Shows title in console window
set ls=2                        " always show status line
set foldmethod=marker           " fold method using markers
set encoding=utf-8              " Set encoding to utf-8

"------------ Graphical block -----------------
syntax on   " Turns on syntax highlighting
color desert
set nu          " Line numbers
filetype plugin indent on

" ----- Key bindings -------
:map cc v:s!^!//!g <CR><CR>
:map cx v:s!^\s*//!!g <CR>v=<CR>
:vmap cc :s!^!//!g <CR>
:vmap cx :s!^\s*//!!g <CR>v=
map <Leader>= :Tabularize /=>/l1<Return>

" File specific settings
autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType javascript setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType json setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType terraform setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType dockerfile set noexpandtab
autocmd BufNewFile,BufRead *.py setlocal ts=4 sts=4 sw=4 expandtab
autocmd BufNewFile,BufRead *.rss setfiletype xml
autocmd BufNewFile,BufRead *.vim setlocal noet ts=4 sw=4 sts=4
autocmd BufNewFile,BufRead *.txt setlocal noet ts=4 sw=4
autocmd BufNewFile,BufRead *.md setlocal spell noet ts=4 sw=4
autocmd BufNewFile,BufRead *.yml,*.yaml setlocal ts=2 sw=2 expandtab

" auto strip whitespace except for file with extention blacklisted
let blacklist = ['diff', 'gitcommit', 'unite', 'qf', 'help', 'markdown']
autocmd BufWritePre * if index(blacklist, &ft) < 0 | StripWhitespace

" vim:ts=2:sw=2:et
