---
- name: 'Create an /etc/sudoers.d entry for this user'
  become: yes
  become_method: sudo
  copy:
    content: |
      {{ account_sudoers_entry }}

    dest: "/etc/sudoers.d/00-{{ account_username }}"
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
