---
- name: 'Create user'
  become: yes
  become_method: sudo
  user:
    name: "{{ account_username }}"
    comment: "{{ account_fullname }}"
    home: "/home/{{ account_username }}"
    shell: '/bin/bash'

- name: 'Add ssh keys from github'
  authorized_keys:
    user: "{{ account_username }}"
    key: "https://github.com/{{ github_username }}.keys"

- name: 'Create an /etc/sudoers.d entry for this user'
  become: yes
  become_method: sudo
  copy:
    content: |
      {{ account_sudoers_entry }}

    dest: "/etc/sudoers.d/00-{{ account_username }}"
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
