---
- name: 'Install git'
  become: yes
  become_method: sudo
  apt:
    name: 'git'
    update_cache: 'yes'
    state: 'latest'

- name: 'Copy gitconfig'
  template:
    src: gitconfig.j2
    dest: "{{ home_directory }}/.gitconfig"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
