---
- name: 'Create sambashare group'
  become: yes
  group:
    name: sambashare
    system: yes
    state: present

- name: 'Create /media directory'
  become: yes
  become_method: sudo
  file:
    path: '/media'
    owner: "{{ directory_user }}"
    group: "{{ directory_group }}"
    mode: '0777'
    state: directory

- name: 'Create /scratch directory'
  become: yes
  become_method: sudo
  file:
    path: '/scratch'
    owner: root
    group: docker
    mode: '0775'
    state: directory

- name: 'Create /srv directories'
  become: yes
  become_method: sudo
  file:
    path: '/srv/filedumpster'
    mode: '0755'
    state: directory

- name: 'Create /data directories'
  become: yes
  become_method: sudo
  file:
    path: '/data'
    mode: '0755'
    state: directory

- name: Create /data subdirectories
  become: yes
  become_method: sudo
  file:
    path: "/data/{{ item }}"
    mode: 0775
    group: docker
    state: directory
  loop:
    - sabnzbd
    - media
