---
- name: 'Create sambashare group'
  become: yes
  group:
    name: sambashare
    system: yes
    state: present

- name: 'Create /scratch directory'
  become: yes
  become_method: sudo
  file:
    path: '/scratch'
    owner: root
    group: sambashare
    mode: '0775'
    state: directory

- name: 'Create /srv directories'
  file:
    path: '/srv/filedumpster'
    mode: '0755'
    state: directory

- name: 'Create /data directories'
  file:
    path:
      - '/data'
      - '/data/sabnzbd'
      - '/data/media'
    mode: '0755'
    state: directory
