---
- name: Install common packages
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - htop
    - weechat
    - curl
    - jq
    - unrar
    - openssl
    - ntpdate
    - python
    - python-pip
    - python-setuptools
    - vim
    - fail2ban
    - gnupg
    - keychain
    - mtr-tiny
    - rar
    - screen
    - tcpdump
    - build-essential
