---
- name: Install common packages
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ apt_packages }}"
    state: present
    update_cache: yes

- name: 'Install apt packages'
  become: yes
  become_method: sudo
  apt:
    pkg: unattended-upgrades
    state: present

- name: 'Adjust APT update intervals'
  become: yes
  become_method: sudo
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
