---
- name: Install common packages
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - htop
    - weechat
    - curl
    - jq
    - unrar
    - openssl
    - ntpdate
    - python
    - python3-pip
    - python3-setuptools
    - vim
    - fail2ban
    - gnupg
    - keychain
    - mtr-tiny
    - rar
    - screen
    - tcpdump
    - build-essential

- name: 'Install apt packages'
  become: yes
  become_method: sudo
  apt:
    pkg: unattended-upgrades
    state: present

- name: 'Adjust APT update intervals'
  become: yes
  become_method: sudo
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic

- name: Install pip packages
  become: yes
  become_method: sudo
  pip:
    name: "{{ item }}"
  executable: pip3
  with_items:
    - docker-py
