---
# directions taken from: https://docs.docker.com/engine/installation/linux/ubuntulinux/

- name: 'Add docker apt repository key'
  become: yes
  become_method: sudo
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: 58118E89F3A912897C070ADBF76221572C52609D
  notify: 'apt-get update'

- name: 'Create docker sources.list file'
  become: yes
  become_method: sudo
  template:
    src: 'docker.list.j2'
    dest: '/etc/apt/sources.list.d/docker.list'
    owner: root
    group: root
    mode: 0644
  notify: 'apt-get update'

- name: 'Install pre-req docker packages'
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- meta: flush_handlers

- name: 'Install docker'
  become: yes
  become_method: sudo
  apt:
    name: 'docker-engine'
    state: present

- name: 'Start docker service'
  become: yes
  become_method: sudo
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'

- name: 'Add user to group docker'
  become: yes
  become_method: sudo
  user:
    name: "{{ docker_username }}"
    group: 'docker'
    append: yes

- name: 'Create docker volume folder'
  become: yes
  become_method: sudo
  file:
    path: '/scratch/docker'
    owner: "{{ docker_username }}"
    group: "{{ docker_group }}"
    mode: '0775'
    state: directory
