---
# directions taken from: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

- name: 'Add docker apt repository key'
  become: yes
  become_method: sudo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  notify: 'Perform an apt-get update'

- name: 'Create docker sources.list file'
  become: yes
  become_method: sudo
  template:
    src: 'docker.list.j2'
    dest: '/etc/apt/sources.list.d/docker.list'
    owner: root
    group: root
    mode: 0644
  notify: 'Perform an apt-get update'

- name: 'Install pre-req docker packages'
  become: yes
  become_method: sudo
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- meta: flush_handlers

- name: 'Install docker'
  become: yes
  become_method: sudo
  apt:
    name:
      - docker-ce
      - docker-compose
    state: present

- name: 'Start docker service'
  become: yes
  become_method: sudo
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'

- name: 'Add user to group docker'
  become: yes
  become_method: sudo
  user:
    name: "{{ docker_username }}"
    group: 'docker'
    append: yes

- name: 'Create docker volume folder'
  become: yes
  become_method: sudo
  file:
    path: '/scratch/docker'
    owner: "{{ docker_username }}"
    group: "{{ docker_group }}"
    mode: '0775'
    state: directory
