---
- name: 'Copy le-renew script'
  action: copy
    src: 'files/le-renew'
    dest: '/usr/local/sbin/le-renew'
    owner: root
    group: root
    mode: '0755'

- name: 'Create cron entry for le-renew'
  action: cron
    name: 'le-renew cert'
    minute: 30
    hour: 2
    month: 1
    user: root
    job: /usr/local/sbin/le-renew {{ le_domain }} >> /var/log/le-renew.log

