---
- name: Create /opt/acme dir
  become: yes
  become_method: sudo
  file:
    path: '/opt/acme'
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Download acme.sh script
  become: yes
  become_method: sudo
  get_url:
    url: https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh
    dest: '/opt/acme/acme.sh'
    group: root
    owner: root
    mode: 0755
