---
- name: 'Add base ubuntu repo'
  become: yes
  become_method: sudo
  template:
    src: 'sources.list.j2'
    dest: '/etc/apt/sources.list'
    owner: root
    group: root
    mode: '0644'
  notify: 'Perform an apt-get update'

- meta: flush_handlers
